config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root "talks#index"
  end
  root "home#index"

  devise_for :users
  resources :talks, only: [:index, :create, :show, :destroy]
  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/talk.rb
class Talk < ApplicationRecord
  acts_as_paranoid

  belongs_to :from_user, class_name: "User", foreign_key: :from_id
  belongs_to :to_user, class_name: "User", foreign_key: :to_id

  default_scope -> { order("talks.created_at") }
  scope :talk_list, -> (user1, user2) {
    user_id1, user_id2 = [user1, user2].map do |user|
      case user
      when Integer
        user
      when String
        User.find_by(user_name: user).id
      when User
        user.id
      else
        raise ArgumentError, "引数の型が不正です"
      end
    end

    where(from_id: user_id1, to_id: user_id2).or \
      where(from_id: user_id2, to_id: user_id1)
  }
end

app/controllers/talks_controller.rb
class TalksController < ApplicationController
  before_action :set_talk, only: [:destroy]
  before_action :authenticate_user!

  # GET /talks
  # GET /talks.json
  def index
    @talkers = current_user.talk_users
  end

  # GET /talks/1
  # GET /talks/1.json
  def show
    @to_user = User.find(params[:id])
    @talks = Talk.talk_list(current_user, @to_user)
  end

  # POST /talks
  # POST /talks.json
  def create
    @talk = Talk.new(talk_params.merge({from_id: current_user.id}))

    respond_to do |format|
      if @talk.save
        format.js
        format.html { redirect_to @talk, notice: 'Talk was successfully created.' }
        format.json { render :show, status: :created, location: @talk }
      else
        format.html { render :new }
        format.json { render json: @talk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /talks/1
  # DELETE /talks/1.json
  def destroy
    respond_to do |format|
      if @talk.from_user == current_user
        @talk.destroy
        format.json { head :no_content }
      else
        format.json { head :unauthorized }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_talk
      @talk = Talk.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def talk_params
      params.require(:talk).permit(:to_id, :content)
    end
end

app/helpers/talks_helper.rb
module TalksHelper
  def relative_date_if_this_week(time, now = Time.now, short: false)
    diff = now - time
    date = time.to_date
    today = now.to_date
    if date == today
      format = "%-H:%M"
    else
      if date == today.yesterday
        format = "昨日"
      elsif diff < 1.week
        format = "#{%w(日 月 火 水 木 金 土)[time.wday]}曜日"
      elsif diff < 1.year
        format = "%-m/%-d"
      else
        format = "%Y/%-m/%-d"
      end
      format << " %-H:%M" unless short
    end
    time.strftime(format)
  end

  def message_to_html(message)
    message = html_escape(message)
    message = make_url_link(message)
    message.gsub(/\R/, "<br />")
  end

  private

  def extract_url(text)
    unreserved_chars = '\w\-_.~'
    reserved_chars = '!$#&\'()*+,/:;=?@\[\]%'
    url_regex = %r!(?:https?|ftp)://[#{unreserved_chars}]+(?:/[#{unreserved_chars}#{reserved_chars}]*)*|mailto:[\w\!$#%&'*+\-/=?^_`{|}~.]+@[\w\-.]+!
    text.scan(url_regex)
  end

  def make_url_link(text)
    url_list = extract_url(text).uniq
    text.gsub(Regexp.union(url_list)) do |url|
      "<a href=\"#{url}\" target=\"_blank\">#{url}</a>"
    end
  end
end

app/views/talks/_form.html.slim
= form_for @talk do |f|
  - if @talk.errors.any?
    #error_explanation
      h2 = "#{pluralize(@talk.errors.count, "error")} prohibited this talk from being saved:"
      ul
        - @talk.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :from
    = f.text_field :from
  .field
    = f.label :to
    = f.text_field :to
  .field
    = f.label :content
    = f.text_area :content
  .field
    = f.label :deleted_at
    = f.datetime_select :deleted_at
  .actions = f.submit

app/views/talks/_talk.html.slim
- is_my_message = (talk.from_user == current_user)
.talk class=(is_my_message ? "my-talk" : "others-talk")
  .talk-info
    - if is_my_message
      = link_to "削除", talk_path(talk), method: :delete, class: "delete-link",
          data: {confirm: "本当に削除しますか？"}, remote: true
      br
    = relative_date_if_this_week(talk.created_at)
  .talk-text
    == message_to_html(talk.content)

app/views/talks/create.js.erb
$("#talks-container").append("<%= j(render @talk) %>")

app/views/talks/edit.html.slim
h1 Editing talk

== render 'form'

=> link_to 'Show', @talk
'|
=< link_to 'Back', talks_path

app/views/talks/index.html.slim
h1 トーク一覧

.card
  ul.list-group.list-group-flush
    - @talkers.each do |talker|
      li.list-group-item
        .talk-summary
          .username
            = link_to talker.display_name, talk_path(talker)
          .last-talk
            = trim_if_long(Talk.talk_list(current_user, talker).last.content, 50)
= link_to "新しい友達を探す", users_path

app/views/talks/new.html.slim
h1 New talk

== render 'form'

= link_to 'Back', talks_path

app/views/talks/show.html.slim
h1 = "#{@to_user.display_name} との会話"
= link_to '戻る', talks_path

#talks-container
  = render @talks
hr
= form_with url: talks_path, scope: :talk, id: "talk-post-form" do |f|
  = f.hidden_field :to_id, value: @to_user.id
  = f.text_area :content
  = f.submit "送信", class: "btn btn-primary"