config/routes.rb
Rails.application.routes.draw do
  authenticated :user do
    root "talks#index"
  end
  root "home#index"

  devise_for :users
  resources :talks, only: [:index, :create, :show, :destroy]
  resources :users, only: [:index, :show]
  resources :friendships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :recoverable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :rememberable, :trackable, :validatable
  devise authentication_keys: [:user_name]

  acts_as_paranoid

  has_many :friendships_from_me, class_name: "Friendship", foreign_key: "user_id"
  has_many :friends, through: :friendships_from_me, source: :to_user

  has_many :friendships_to_me, class_name: "Friendship", foreign_key: "friend_id"
  has_many :followers, through: :friendships_to_me, source: :from_user

  has_many :talks_from_me, class_name: "Talk", foreign_key: "from_id"
  has_many :users_talking_to, through: :talks_from_me, source: :to_user

  has_many :talks_to_me, class_name: "Talk", foreign_key: "to_id"
  has_many :users_talking_to_me, through: :talks_to_me, source: :from_user

  validates :user_name, presence: true, uniqueness: {scope: :deleted_at},
            format: {with: /\A[\w_]+\z/, message: "英数字とアンダーバー(_)のみ使用できます"}

  def talk_users
    id_list = users_talking_to.pluck(:id) | users_talking_to_me.pluck(:id)
    User.where(id: id_list)
  end

    def email_required?
    false
  end

  def added_friend?(user)
    friends.include? user
  end

  def friendship_to(user)
    friendships_from_me.find_by(friend_id: user.id)
  end

  def friendship_from(user)
    friendships_to_me.find_by(user_id: user.id)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # # GET /users/new
  # def new
  #   @user = User.new
  # end

  # # GET /users/1/edit
  # def edit
  # end

  # # POST /users
  # # POST /users.json
  # def create
  #   @user = User.new(user_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # PATCH/PUT /users/1
  # # PATCH/PUT /users/1.json
  # def update
  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @user }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /users/1
  # # DELETE /users/1.json
  # def destroy
  #   @user.destroy
  #   respond_to do |format|
  #     format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:user_name, :display_name)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_add_friend_button.html.slim
= form_with url: friendships_path, scope: :friendship, class: "add-friend" do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :friend_id, value: user.id
  = button_tag class: "btn btn-outline-primary" do
    .inner-button 追加

app/views/users/_form.html.slim
= form_for @user do |f|
  - if @user.errors.any?
    #error_explanation
      h2 = "#{pluralize(@user.errors.count, "error")} prohibited this user from being saved:"
      ul
        - @user.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user_name, "ユーザーID"
    = f.text_field :user_name
  .field
    = f.label :display_name, "ユーザー名"
    = f.text_field :display_name
  .field
    = f.label :password, "パスワード"
    = f.text_field :password
  .field
    = f.label :password_confirmation, "パスワード（確認）"
    = f.text_field :password_confirmation
  .actions = f.submit "登録"

app/views/users/_remove_friend_button.html.slim
= form_with model: friendship, method: :delete, class: "remove-friend" do |f|
  = button_tag class: "btn" do
    .inner-button#text-added 追加済み
    .inner-button#text-remove 解除

app/views/users/edit.html.slim
h1 Editing user

== render 'form'

=> link_to 'Show', @user
'|
=< link_to 'Back', users_path

app/views/users/index.html.slim
h1 ユーザー一覧

.card
  ul.list-group.list-group-flush
    - @users.each do |user|
      li.list-group-item
        .user-summary
          span.username
            = link_to user.display_name, user
          - if current_user == user
            = link_to "プロフィール更新", edit_user_registration_path, class: "btn btn-outline-primary"
          - else
            - if current_user.added_friend? user
              = render "remove_friend_button", friendship: current_user.friendship_to(user)
            - else
              = render "add_friend_button", user: user

app/views/users/new.html.slim
h1 New user

== render 'form'

= link_to 'Back', users_path

app/views/users/show.html.slim
p#notice = notice

h1 = @user.display_name

- if @user == current_user
  = link_to "プロフィール変更", edit_user_registration_path
- else
  = link_to "このユーザーとの会話", talk_path
br
= link_to '戻る', users_path